gText_Host_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Survival Island!\n"
	.string "I am DONATHAN, your host.\p"
	.string "Survival Island is a timed-”\n"
	.string "attack survival-based game\l"
	.string "involving POKéMON and trainers.\p"
	.string "$"

gText_Host_Pokemon::
	.string "As you are probably aware, this\n"
	.string "is a POKéMON.\p"
	.string "$"

gText_Host_MainSpeech::
	.string "Survival island is a tough\n"
	.string "challenge that tests a trainers\l"
	.string "mettle and knowledge in POKéMON.\p"
	.string "It is not for the faint hearted.\n"
	.string "You, as a trainer, are tasked with\l"
	.string "reaching the end of the island,\l"
	.string "battling trainers along the way,\l"
	.string "aided by the POKéMON you have\l"
	.string "captured.\p"
	.string "It is a difficult task, but you\n"
	.string "will have the help of items and\l"
	.string "materials along the way.\p"
	.string "I hope you are up to the\n"
	.string "challenge!\p"
	.string "$"

gText_Host_DescribeYourself::
	.string "To clarify to the audience that\n"
	.string "will be watching your every move,\l"
	.string "describe yourself a little.$"

gText_Host_ManOrWoman::
	.string "Are you a man?\n"
	.string "Or are you a woman?$"

gText_Host_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Host_SoItsPlayer::
	.string "To clarify, you're {PLAYER}{KUN}?$"

gText_Host_YourePlayer::
	.string "Alright. Spectators and viewers,\n"
	.string "let's welcome {PLAYER}{KUN}\l"
	.string "to the gameshow\l" 
	.string "SURVIVAL ISLAND!\p"
	.string "$"

gText_Host_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your journey through SURVIVAL\n"
	.string "ISLAND is about to begin!\p"
	.string "Remember, to progress, you must\n"
	.string "reach the final area and beat the\l"
	.string "boss at the end of the island.\p"
	.string "Then, and only then, will you be\n"
	.string "crowned a SURVIVALIST. Good luck!\p"
	.string "$"
